### ISSUE TITLE
iPhone portrait/landscape orientation bug

### ISSUE THREAD

**Issue by thumpclang** [danomatika/PdParty#101]
In PdParty 1.3.2 I'm observing a difference in how my iPhone (SE 2nd gen, iOS 16.1.2) handles auto-orientation versus my iPad (5th gen, iPadOS 16)

When opening TriSamp (or other landscape orientation patches) while holding the iPhone in portrait orientation, it looks like PdParty is failing to lock into either orientation & getting stuck in an endless loop. Opening the upper right menu stops this behavior, after which auto-orientation works as expected (at least until the patch is re-opened).

The screen recording below begins with the iPhone held steadily in portrait; at 6 seconds in, I rotate the phone to landscape to stop the bouncing, then after opening the upper right menu (and opening the console in this case), I rotate back to portrait at the 11 second mark & PdParty remains locked into landscape orientation.

https://user-images.githubusercontent.com/88018389/212163997-fbae82bf-9908-41c8-9cb1-a2dd6f2dbc93.MP4

For comparison, here is TriSamp opened on iPad in portrait, at 4 seconds rotated to landscape, at 6 seconds back to portrait:

https://user-images.githubusercontent.com/88018389/212164057-4f061e7f-872b-42de-b53b-2d95788eb91d.MP4

Not a big problem since there's a workaround, but I stumbled across this today & figured I'd report it in case it's an easy fix.

**Comment by danomatika** [comment]
I might have to simply disable animation when changing rotation, although the visual feedback will be lost.

**Comment by danomatika** [comment]
> figured I'd report it in case it's an easy fix.

The thing is... it should already have been fixed in the latest release. I saw this firsthand when giving a workshop in November 2022 and thought I had fixed it by the releases in December.

The problem is, I have an *ancient* iPhone by modern standards which has never triggered this behavior (6S). So far I prioritize parts for my road bike over a new 800+ EUR iPhone ;) and an older iPhone does everything I need of it when performing live with PdParty.

I will try to look into this as I am doing (commissioned) work on PdParty ATM for September.

**Comment by thumpclang** [comment]
> I prioritize parts for my road bike over a new 800+ EUR iPhone ;)

I think your priorities are on point. :p I'd still be rocking my 6s if not for a free hand-me-down SE.

Thanks for looking into this bug! As mentioned it's not really a show stopper, just a minor curiosity.

**Comment by danomatika** [comment]
I can confirm that I am able to trigger this behavior in the Simulator, specifically with the iPhone SE 3. When I worked on this issue last November, I tested with my wife's iPhone 13 Pro but not specifically with the simulator. Often these kinds of things are down to timing where sometimes it's ok and other times a little delay would fix it.

**Comment by danomatika** [comment]
After trying quite a few different things over the last months, I went back to the Apple docs and realized there is a new flag which needs to be set if you change the interface orientation: 336c9e702eea9782d9792bddba9d7318496dc7b7

This stops the dancing behavior and will be in the next beta test release.

**Comment by danomatika** [comment]
PdParty 1.4.0-beta3 is now on TestFlight. Please test and close this issue if it is fixed.

**Comment by Josef-N** [comment]
no more dancing on my device:
iPhone 12, iOS 17.1
This issue is fixed, as far as I can see

**Comment by danomatika** [comment]
FWIW, the devices I have checked are an iPhone 13 mini with iOS 16 and an iPhone 6S with iOS 14. The API change came with iOS 16, so only newer devices were affected, AFAICT.

**Comment by thumpclang** [comment]
Can confirm that the dancing is resolved in PdParty 1.4.0-beta3 (on iPhone SE 2nd gen, iOS 17.0.3). Thanks!
