### ISSUE TITLE
Increase max MIDI devices and/or improve device selection

### ISSUE THREAD

**Issue by danomatika** [danomatika/PdParty#104]
The current maximum number of MIDI input and output devices is 4, however some projects may require more, ie. a single device might expose more than 1 MIDI device and the available slots can fill up quickly.

The simple solution is to increase the max here to maybe 8 or 16: https://github.com/danomatika/PdParty/blob/master/src/modules/MidiBridge.h#L14

4 was chosen in an attempt to match Pd vanilla's "multi device mode" which gives you 4 available inputs and outputs, however this still allows you to choose among *more* than 4 devices into the available slots.

A possibly better, but more complicated version, would be a more advanced picker instead of simply bubbling up the first 4 input or output devices. Another option would be to make the max allowed selectable.

**Comment by Josef-N** [comment]
yes, please! As much ports as possible, even 8 would not be sufficient for me.
I am frequently getting into trouble when I would need a port that is not listed.

**Comment by danomatika** [comment]
I looked at this and my update would be the following:
* keep the 4 inputs and 4 outputs limitation, like desktop Pd
* expand the Multi-Device Mode table to show up to 16 of each, only the first 4 are "active"
* to activate device, edit and reorder so the devices you need are 1-4

This involves the minimum of changes without a large change to the GUI.

**Comment by Josef-N** [comment]
This is a good solution, I think.
In my case, I would need only 2 or 3 ports. Reordering is no problem, as long as the other ports are visible.

**Comment by danomatika** [comment]
Latest commit in `develop` now has the following behavior:

Multiple Device Mode enabled
* max 4 inputs and 4 outputs, like desktop Pd
* input & output tables now shows up to 16 of each, only the first 4 are always shown and can be "active"
* to activate a device, edit and reorder so the devices you need are 1-4

Multiple Device Mode disabled
* all devices share port 0 (up to max 16...)

I decided to not limit to max 4 when multi device mode is disabled because you might reorder the ports if you have more than 4 devices and wonder why they don't *all* receive MIDI messages. The simplest conceptually approach is have them all work when you don't care about addressing specific devices through specific ports, ie. you use channels and port 0.

The table will always show 4 devices and any additional devices, up to 16 in total. Here is an example where it shows all 16 devices... in this case, temp data:

![Simulator Screenshot - iPhone SE (3rd generation) - 2023-09-04 at 21 11 29](https://github.com/danomatika/PdParty/assets/480637/bff3bf36-bd87-4a30-a032-9d5c3cb9d6e3)

**Comment by Josef-N** [comment]
great, this is perfect!

**Comment by danomatika** [comment]
PdParty 1.4.0-beta3 is now on TestFlight. Please test and close this issue if things work as expected.

**Comment by Josef-N** [comment]
Yes, it works on my devices, fantastic! Now I get back some ports I have been missing since long.

**Comment by Josef-N** [comment]
I don’t know how to close this issue, could you do it please?
