### ISSUE TITLE
multitouch on canvas, again

### ISSUE THREAD

**Issue by Josef-N** [danomatika/PdParty#105]
This has already been extensively discussed in #79. At the end you wrote, that it should be implemented in PdParty 1.3.0:

> Back to the original topic: I have this working now but decided to leave it off by default. There is new behavior, however, where canvas and comments forward touch events always and I think this gets to the heart of the issue at hand.

What I see: comments forward all touch events (multiple touch id’s), same behavior as in 1.2.0.
canvas – only touch id 1 (same as before).

Why I am asking:
I am absolutely fascinated by the ViewPort method, and I am looking forward to the dynamic background in 1.4.0. But my main patch uses multitouch, so I just cannot use ViewPort, because the whole screen would be a canvas then.
It is really a pity, that ViewPort and multitouch cannot be used in combination, they exclude each other.
It would be great, if you could look at it again for 1.0.4

**Comment by danomatika** [comment]
Why not enable touch everywhere? It was added in 1.3.0 -> https://github.com/danomatika/PdParty/blob/master/doc/guide/PdParty_User_Guide.md#everywhere

**Comment by danomatika** [comment]
Ah, I understand now. You mean that widgets only report single touches but the background reports multiple. I just need to set `multipleTouchEnabled = YES` on certain widgets, as you suggest canvas and comment at a minimum. I don't think it's needed for single-input widgets like bang, toggle, radio, slider and would greatly probably not work very well.

**Comment by danomatika** [comment]
Ok, the next beta will have the following behavior:
* comment & canvas have multitouch enabled
* comment & canvas *always* forward touch events regardless of everything setting

Also, ViewPort handling is changing to where it is no longer drawn on the screen and it doesn't take any touch events. I didn't realize DroidParty doesn't;t draw it and am rectifying that now.

**Comment by danomatika** [comment]
1.4.0-beta2 is now on TestFlight

**Comment by Josef-N** [comment]
Wonderful, thank you!
Just looked at the [Touch] scene in tests/pdparty. It is exactly what I meant. And I absolutely agree that it’s not needed for widgets like slider, toggle and so on.

**Comment by danomatika** [comment]
> It is exactly what I meant.

As in it's working as you need now?

> And I absolutely agree that it’s not needed for widgets like slider, toggle and so on.

Actually, I looked and multitouch is enabled for things which allow two-finger drag for fine tuning which approximates SHIFT-drag on desktop. With touch everywhere enabled, these events are forwarded a well so the only things which might swallow multitouch are toggle, bang, and the like.

**Comment by Josef-N** [comment]
> As in it's working as you need now?

Yes, that’s perfect.
I did not try touch everywhere yet, but this is also an interesting option. Good, that you mentioned two-finger drag, I was not aware of that.

**Comment by danomatika** [comment]
I added a note about this: https://github.com/danomatika/PdParty/commit/c28f65040a88b4c33e2725410260a463a80e178d

**Comment by Josef-N** [comment]
Great, thanks! I added a note about this: c28f650—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Josef-N** [comment]
thanks!
