### ISSUE TITLE
feature request: autoload patch on app startup

### ISSUE THREAD

**Issue by offthesky** [danomatika/PdParty#106]
love this app!! would be great to be able to somehow set a patch to open automatically when the app starts up. 

or, if this is already a feature in the app (didn't find anything pertaining to this in the user guide) would love to know how, tia!

**Comment by danomatika** [comment]
I can think about it, but I would say this feature would not be high on my list.

**Comment by offthesky** [comment]
certainly no worries if its super low(or no) prio.  guessing im one of the few that uses pdparty in a larger scale across many devices for live sets(and occasional installations), having to reset+reload the app and patches w each device before each performance. regardless, do really appreciate your actually considering the idea!

**Comment by danomatika** [comment]
Have you tried using the iOS URL scheme? http://danomatika.com/code/pdparty/guide#pdpartyurlscheme

You could basically have users open a URL on a webpage, in an email, in a PDF, in a QR code, etc which then invokes the app to open a specific scene. It should also open the app when it's not running.

**Comment by offthesky** [comment]
it seems like that would be the way to go. especially since one can create a url link on their home screen. but i always get a popup in safari: "safari cannot open the page because the address is invalid"- even using the test url you posted in the guide this error occurs: pdparty://open/tests/all_pd_guis.pd - not sure what im doing wrong.

**Comment by danomatika** [comment]
You are probably not doing anything wrong. Something could have changed and the url scheme is not being registered with iOS correctly.enohp ym morf tnes-----------Dan Wilcoxdanomatika.comrobotcowboy.comOn Oct 17, 2023, at 3:51 PM, jason corder ***@***.***> wrote:﻿
it seems like that would be the way to go. especially since one can create a url link on their home screen. but i always get a popup in safari: "safari cannot open the page because the address is invalid"- even using the test url you posted in the guide this error occurs: pdparty://open/tests/all_pd_guis.pd - not sure what im doing wrong.

**Comment by danomatika** [comment]
I will check if this still works. In the meantime, you could try a 1.4.0 beta via TestFlight: https://testflight.apple.com/join/17ZZ5AC7

**Comment by offthesky** [comment]
i think for the most part it seems to be working predominantly okay via 1.4.0. certainly works more consistent than before.

i did however receive the address is invalid error a few times, but not entirely sure what i did to make that happen. it seems if you kill safari and restart it though, the url worked ok afterwards

**Comment by offthesky** [comment]
well shoot, im trying the url again this morning and its consistently erroring out, stuck in a bad state. it was working ok just yesterday.  curious what could cause this

**Comment by danomatika** [comment]
I may some changes to fix how opening files and zips works and, I think, broke the pdparty:// URL handling. I will fix it.

**Comment by danomatika** [comment]
Are you using `pdparty://open` in your URL?  ex. `pdparty://open/tests/all_pd_guis.pd` This works fine in my testing. The **open** part is important as it is used as a message type

What is inconsistent is `pdparty://...` with anything else. I have added explicit handling now to ignore non **open** message types and simply open the app. This could explain what you are seeing.

**Comment by offthesky** [comment]
i'm definitely using pdparty://open/ format.  also im currently using devices with ios15.7.9

**Comment by danomatika** [comment]
PdParty 1.4.0-beta3 is now on TestFlight with the url handling improvements. Please test.

Howto: Install the free TestFlight app on your iDevice, then open this TestFlight link:

https://testflight.apple.com/join/17ZZ5AC7

**Comment by offthesky** [comment]
tried out the new version, about the same results as before. mostly works, but at times errors out with safari stating the address is invalid. i think ive pinpointed the steps that cause this error:
1 create a favorites link in safari pointing whatever url
2 edit that link, change the url to pdparty://open/tests/all_pd_guis.pd
3 tap that favorites link, you get a popup asking "open this page in "pdparty"?
4 hit cancel, then after that safari is stuck in the 'address is invalid' state until you kill/restart safari

imho this url handling thing is not more useful or efficient for a startup patch, than the regular method of opening a patch. creating a "pdparty://open/" (non web resolvable) link on the home screen is not a sturdy method: you have to enter that non-web link in safari, hit go, and when you get the "open this page in "pdparty"? pop up, you have to kill safari, reopen the app, then the url is actually there waiting in the bottom address bar with the share icon enable(that icon wont be active unless you kill safari first). even still, after tapping on a home screen link to a patch, you have safari loading and hanging out in the background forcing you to manually kill it, to free up the most ram for the safest live performance environment... and of course that 'add non-web link to home screen' method above doesn't work on older ios (tried on my ios12 tablets) so honestly, it really just makes sense to use the usual method of loading up a patch.

i do hope at some point we could have an option to autoload a patch, even if it's hardcoded to work with some preset filename (i.e. startup.pd, onload.pd, etc)..

**Comment by danomatika** [comment]
You don't have to use just Safari. Is the same true if the link is clicked from the Notes app? The thing is: I can't control the "invalid link" part, PdParty has registered the "pdparty://" protocol and it then receives the URL. I'll double check this.enohp ym morf tnes-----------Dan Wilcoxdanomatika.comrobotcowboy.comOn Nov 9, 2023, at 8:14 PM, jason corder ***@***.***> wrote:﻿
tried out the new version, about the same results as before. mostly works, but at times errors out with safari stating the address is invalid. i think ive pinpointed the steps that cause this error:
1 create a favorites link in safari pointing whatever url
2 edit that link, change the url to pdparty://open/tests/all_pd_guis.pd
3 tap that favorites link, you get a popup asking "open this page in "pdparty"?
4 hit cancel, then after that safari is stuck in the 'address is invalid' state until you kill/restart safari
imho this url handling thing is not more useful or efficient for a startup patch, than the regular method of opening a patch. creating a "pdparty://open/" (non web resolvable) link on the home screen is not a sturdy method: you have to enter that non-web link in safari, hit go, and when you get the "open this page in "pdparty"? pop up, you have to kill safari, reopen the app, then the url is actually there waiting in the bottom address bar with the share icon enable(that icon wont be active unless you kill safari first). even still, after tapping on a home screen link to a patch, you have safari loading and hanging out in the background forcing you to manually kill it, to free up the most ram for the safest live performance environment... and of course that 'add non-web link to home screen' method above doesn't work on older ios (tried on my ios12 tablets) so honestly, it really just makes sense to use the usual method of loading up a patch.
i do hope at some point we could have an option to autoload a patch, even if it's hardcoded to work with some preset filename (i.e. startup.pd, onload.pd, etc)..

**Comment by danomatika** [comment]
I am not seeing any issues with my limited testing on iOS 14 and iOS 16. Opening via `pdparty://open/tests/all_pd_guis.pd` works without issue in Safari from the address bar or as a favorites link.  Out also works fine as a link in the Notes app. I'm not saying I don't believe you, just noting that my devices running probably new versions of iOS have no issues with this.

> i do hope at some point we could have an option to autoload a patch, even if it's hardcoded to work with some preset filename (i.e. startup.pd, onload.pd, etc)..

That is not a bad idea. I am unwilling to add such an option to the GUI for various reasons, but a configuration file could be acceptable. This is also probably easy to deal with when deploying the same setup onto many devices.

> i am curious now, what other useful use cases are there for this kind of url handling/open method, beyond just for startup patches?

Mainly for creating links to things in other apps. See #61. @Josef-N How do you use `pdparty://open`?

**Comment by offthesky** [comment]
> You don't have to use just Safari. Is the same true if the link is clicked from the Notes app? The thing is: I can't control the "invalid link" part, PdParty has registered the "pdparty://" protocol and it then receives the URL. I'll double check this.

ah, didn't think to use anything other than the link on home screen via safari. it seems to work ok no problem via notepad

**Comment by offthesky** [comment]
> That is not a bad idea. I am unwilling to add such an option to the GUI for various reasons, but a configuration file could be acceptable. This is also probably easy to deal with when deploying the same setup onto many devices.
> 
a config there would certainly be v welcome/useful. totally get not wanting to muddy up the gui/ux

> 
> Mainly for creating links to things in other apps. See #61. @Josef-N How do you use `pdparty://open`?
ty!!

**Comment by offthesky** [comment]
> I am not seeing any issues with my limited testing on iOS 14 and iOS 16. Opening via `pdparty://open/tests/all_pd_guis.pd` works without issue in Safari from the address bar or as a favorites link. It also works fine as a link in the Notes app. I'm not saying I don't believe you, just noting that my devices running probably new versions of iOS have no issues with this.
> 
> >

its interesting, this error for me is only reproable in safari on my ios16 device, but doesn't occur in safari on my ios12 device. who knows...

**Comment by Josef-N** [comment]
> How do you use pdparty://open? 

actually I am using only pdparty:// to switch quickly between MidiDesigner and PdParty. MidiDesigner can do it also. In both apps I have buttons that send custom urls (also to launch other apps).
The first thing I tried already in 2017 was opening urls in Safari. You are asked each time for permission – that did not change until today. In other apps that can create links (Notes, text editors, pdf) you are asked only once, and that’s it.
Now I tried to open some patches in Notes with pdparty://open/... and found no problem, with pure pd patches as well as with scenes (name of the folder).
Tested on iPad Pro, 11", 3rd Gen, OS 17.1.1 and on
iPhone 12, OS 17.1.1
in PdParty 1.4.0-beta3

**Comment by danomatika** [comment]
Please try 1.4.0-beta4. It includes support for `config.json` including setting a startup path. Details are in the [user guide section](https://github.com/danomatika/PdParty/blob/develop/doc/guide/PdParty_User_Guide.md#startup-configuration-file-configjson)

**Comment by offthesky** [comment]
so far the startup path/config.json seems to work like a charm, bravo TY!! :]

**Comment by Josef-N** [comment]
I was just about to make a suggestion for an easy way to autoload via custom url: create a document in the Shortcuts app and add it to the homescreen.
But the new option for the settings file is much better or course, great!

**Comment by offthesky** [comment]
> actually I am using only pdparty:// to switch quickly between MidiDesigner and PdParty. MidiDesigner can do it also. In both apps I have buttons that send custom urls (also to launch other apps).

thank you for mention this (as well as shortcuts app, completely forgot about that one), as i need to implement something like this button<app switch method on a couple of the devices

**Comment by danomatika** [comment]
PdParty 1.4.0 is now available on the App Store.

**Comment by Josef-N** [comment]
fantastic, thank you!
