### ISSUE TITLE
advanced DroidParty abstraction support

### ISSUE THREAD

**Issue by danomatika** [danomatika/PdParty#28]
Support for the advanced DroidParty abstractions:

- [x] [ribbon]
- [x] [mknob]
- [x] [loadsave]
- [x] [menubang]
- [x] [droidsystem]
- [x] ~~[droidnetclient]~~ DEPRECATED
- [x] ~~[droidnetreceive]~~ DEPRECATED

**Comment by danomatika** [comment]
[loadsave] now done with file browser rewrite

**Comment by danomatika** [comment]
@chr15m [droidnetreceive] relies on [netclient] which doesn't create in libpd for me, are the netreceieve and nested objects up to date?

**Comment by chr15m** [comment]
`droidnetreceive` and `droidnetsend` existed because there was a bug in libpd which stopped `netreceive` from working. that was fixed last year so those objects are deprecated.

i am not sure if ribbon ever worked! i don't remember now.

**Comment by danomatika** [comment]
[ribbon] does work. Is it deprecated? If so, I'll stop working on my version ...

**Comment by chr15m** [comment]
i am not sure. i don't remember if i ever used it, and i don't know if anybody else ever used it. sorry to be vague!

**Comment by danomatika** [comment]
How does [menubutton] work? I read the description and looked at the code and have a general understanding, but what menu are the buttons attached to? Is it something that appears when you click on something or? I couldn't find any screenshots ...

**Comment by chr15m** [comment]
Here's an example of the menu that appears in PdDroidParty when you hit 
the Android built-in 'menu' button.

![](http://lists.puredata.info/pipermail/pd-list/attachments/20110905/79e63abf/attachment-0003.png)

What the menubutton abstraction lets you do is add an item to this menu 
(by default it contains "about" and "exit") and the item you nominate 
will get added to the menu and when the user selects it the menubutton 
object will output a bang.

**Comment by danomatika** [comment]
Ah ok, it's the OS menu option. I forget about that since I don't use Android and the UI is a little different than iOS in that regard.

**Comment by danomatika** [comment]
Seems like overtime I check, there are new DroidParty objects! My goal is to replicate the droidparty interface as much as possible so, like with RjDj projects, things will *just work*. Maybe we can standardize an interface later on, but for now, it seems better to match what's already there.

A few questions:

* Can I replicate [droidnetclient] & [droidnetreceive] using wrapper abstractions around [netsend] & [netreceive]? Or should I not bother since everything works natively?
* Are the accel, gps, etc events disabled by default and enabled using [droidsystem]?
* if the directory argument is set, [loadsave] opens a file picker *only* in the given directory. Otherwise, the picker opens in the current scene dir. How does it handle this in DroidParty?

**Comment by danomatika** [comment]
[droidsystem] now working via an abstraction wrapper around #pdparty messaging.

**Comment by danomatika** [comment]
added background png support

**Comment by danomatika** [comment]
mknob is done:

<img width="432" alt="screen shot 2015-12-27 at 1 49 42 pm" src="https://cloud.githubusercontent.com/assets/480637/12011937/c77838bc-aca0-11e5-8654-22c81d3ad804.png">

**Comment by danomatika** [comment]
![droidparty menu](https://cloud.githubusercontent.com/assets/480637/12076848/cac77e94-b17b-11e5-95b5-b05af23956db.png)

**Comment by danomatika** [comment]
Menubang done:

<img width="680" alt="screen shot 2016-01-08 at 4 44 27 pm" src="https://cloud.githubusercontent.com/assets/480637/12212400/24ee332c-b627-11e5-800a-c7632f213c70.png">
