### ISSUE TITLE
[numberbox] and other PdDroidParty UIs should accept a "set ..." message which sets the value displayed without outputting the update.

### ISSUE THREAD

**Issue by chr15m** [danomatika/PdParty#34]

**Comment by danomatika** [comment]
Which ones specifically?

**Comment by danomatika** [comment]
Also, would be nice if the individual droipdarty abstractions had help files. The Overview is great, but I keep right clicking -> help ...

**Comment by danomatika** [comment]
Ok, in looking at the abstractions:

* **numberbox**: set float (I have that done now)
* **menubang**: set?
* **taplist**: set list of symbols?
* **display**: set symbol?
* **touch**: set x y position?
* **ribbon**: set left right positions?
* **wordbutton**: set symbol?
* **load save**: none

**Comment by danomatika** [comment]
Related development to #28

**Comment by danomatika** [comment]
Checking against the current DroidParty abstractions:

* **menubang**: none
* **taplist**
  * receive bang, receive index, receive set index, receive-list list
  * send symbol, send/idx index
* **display**
  * receive float, receive symbol, receive list
* **touch**
  * send list
* **ribbon**
  * send list
* **wordbutton**
  * send bang
* **numberbox**
  * send float
  * receive float, receive set float
* **loadsave**
  * send path, send-detail ext file dir
  * receive load dir ext, receive save dir ext
