### ISSUE TITLE
Crash on display of large numbers in a small number box.

### ISSUE THREAD

**Issue by monkeyswarm** [danomatika/PdParty#35]
Display a large number in a number box of width = 5.
Expected behavior: display of "+" (or "-" for negative).
Actual: crash from an out of bounds error.
[__NSCFString replaceCharactersInRange:withString:]: Range or index out of bounds'

It occurs in Widget.m line 257, because string.length is 1 (having been set to "+" in line 242), and thus "old_exp_index" has a value of -3 at ln 254.

**Comment by danomatika** [comment]
Ok. I need to check atom & nbx to see if they handle the width=0 situation aka self sizing anyway.

**Comment by danomatika** [comment]
Still seeing this in testing.
