### ISSUE TITLE
Allow widget subclasses to use factory creation methods.

### ISSUE THREAD

**Issue by monkeyswarm** [danomatika/PdParty#39]
Hi Dan, thanks for the recent refactoring that makes Gui.h easier to subclass. It's a great help. One more tweak would allow easier subclassing of the widget classes as well.

In each widget's class method for creation (e.g. toggleFromAtomLine:withGui), it allocs an object of the base class, not of a subclass.
Replace each use of 
Toggle *x = [[Toggle alloc] initWithFrame:]
with
Toggle *x [[[self class] alloc] initWithFrame:]
to alloc the subclass.

**Comment by danomatika** [comment]
I consolidated the init code into Widget initWithAtomLine:andGui:. Subclasses only need to override this and I got rid of the Class method creators.
