### ISSUE TITLE
Radio default value.

### ISSUE THREAD

**Issue by monkeyswarm** [danomatika/PdParty#43]
Radio.m gets its value from atomline[6]. However, that value is not the value written by initial value, but (according to https://puredata.info/docs/developer/PdFileFormat#r34) a switch value that is not used. This means that radios are being initialized to value of 1 unexpectedly.
Radio shouldn't get a value unless "init" is on, and then it should behave as it currently does, to read a separate init value at the end of the atom line.
Thanks!

**Comment by danomatika** [comment]
Good catch. I didn't know of the file format doc and basically worked from reading the pd files themselves :P
