### ISSUE TITLE
Radio widget layout drawing.

### ISSUE THREAD

**Issue by monkeyswarm** [danomatika/PdParty#51]
the frame computation in [Radio reshape] determines the bounds of the view by:

`float cellSize = ceil(self.size * self.gui.scaleX);`

but the cells themselves are drawn in drawRect with:

`float cellSize = round(self.size * self.gui.scaleX);`

Thus yielding the attached image.
I'm exporting a pull request that merely changes the bounds computation to also use |round|.
![simulator screen shot jan 28 2016 10 55 43 am](https://cloud.githubusercontent.com/assets/1235083/12658083/bfbc415c-c5bb-11e5-9f87-304efce8dee5.png)

**Comment by danomatika** [comment]
Looks like that was leftover from when I was trying to keep the active cell indicator from getting "out of square". I tried a number of combinations of round, ceil, floor, etc but looks like I didn't revert everything.

**Comment by danomatika** [comment]
Next commit will include a fix for the radio indicator sizing. The issue was than when radio starts to get small (i.e. a large canvas patch on iPhone), the indicator gets too small and offset in the wrong position.

**Comment by danomatika** [comment]
Should be fixed now.
