### ISSUE TITLE
Replacement of dollar-sign-zero values does not work

### ISSUE THREAD

**Issue by monkeyswarm** [danomatika/PdParty#53]
- Create a pd patch with a single gui item. Give it a label/sendname/receivename using $0, e.g. $0-foo.
- Expected: label is shown in PdParty as the assigned number, e.g. "1003-foo". 
- Actual: shown as "#0-foo".

Even though the user writes $0, it is actually encoded in the .pd file atom line as $0:
`#X floatatom 69 17 5 0 0 0 #0-baz #0-bar #0-foo, f 5;`
And so is not caught by Gui.m line 282, which scans for "\\$0". 
Did pd used to encode '$0' that way? Is it as simple as switching the match pattern to "#0" or is there more complexity at work here?

![file_000](https://cloud.githubusercontent.com/assets/1235083/12739938/297b73b4-c923-11e5-9417-5a33628315fd.png)

**Comment by danomatika** [comment]
It's just a find and replace. I had it in there a long time ago after the port of some stuff from PdDroidParty but never saw it being used and thought it wasn't needed, so I remove it. Guess it needs to come back.

**Comment by danomatika** [comment]
Also, which version of pd did you use to create the file?

**Comment by danomatika** [comment]
Ok I just checked, the behavior is the same from Pd-extended (0.43) as well as the current vanilla release (0.46-7).

**Comment by danomatika** [comment]
Ok, this is confirmed as fixed. Just did a string replace for "#0" and added dollartest.pd:

<img width="432" alt="screen shot 2016-02-02 at 2 01 10 pm" src="https://cloud.githubusercontent.com/assets/480637/12764237/d1ac9b20-c9b5-11e5-984f-af7861f5c1d6.png">

**Comment by danomatika** [comment]
Hah, now I see the $0 is replaced in the comment. Whoops. I'll double check where the replacement is happening through the UIS.

**Comment by danomatika** [comment]
I did some digging and I noticed that the float & symbol atoms save "$0" as "#0" while the iem guis save it as "\$0". All of my tests up to this point did not use $0 in the label or send/receive names. Thanks for finding this.

**Comment by danomatika** [comment]
Ok, this should all be fixed now:

<img width="432" alt="screen shot 2016-02-02 at 2 01 10 pm" src="https://cloud.githubusercontent.com/assets/480637/12765791/7ec9b552-c9bd-11e5-907d-d98e981b2484.png">
