### ISSUE TITLE
Linker fails on liblo

### ISSUE THREAD

**Issue by monkeyswarm** [danomatika/PdParty#54]
On build/run from XCode:

ld: library not found for -llo
clang: error: linker command failed with exit code 1 (use -v to see invocation)

The XCode proj shows red for libs/liblo/liblo.a. Missing the file in repo?

**Comment by danomatika** [comment]
Yup. Filtered by my ignore rules. In the long run it might be better to rely on the script which builds and downloads liblo to keep the repo from getting cluttered with binaries: `scripts/libs/update_liblo.sh`
