### ISSUE TITLE
Linker Error on Build

### ISSUE THREAD

**Issue by lukemorse** [danomatika/PdParty#58]
I got several errors relating to pd, pd folder was empty.  After cloning libpd, those errors went away but I'm still getting a Linker Error.  Any ideas?

Apple Mach-O Linker Error Group
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thanks,
Luke

**Comment by danomatika** [comment]
You need to check out the submodules as well.

Also, why are you building from source? The app is available on the App Store.

**Comment by danomatika** [comment]
Ah ok, I see now you did clone the submodule, but did you do it recursively so the libpd/pure-data folder is populated as well?

**Comment by lukemorse** [comment]
I tried your "git submodule foreach --recursive init" but it didn't seem to do anything for pd, so I cloned that separately.

**Comment by lukemorse** [comment]
Hey, I got it working with `git submodule update --init --recursive`
