### ISSUE TITLE
(undocumented) color message is ignored in PdParty

### ISSUE THREAD

**Issue by toniarnold** [danomatika/PdParty#59]
I've read about the color message at https://forum.pdpatchrepo.info/topic/9965/canvas-colors

In `bulbs.py`, the message argument gets composed with:

    def rgb_2_color(r, g, b):
        """Konversion RGB zu PureData RGB color

        >>> rgb_2_color(255, 255, 255)
        -16777216
        >>> rgb_2_color(0, 0, 0)
        -1
        """
        val = - 1 - ((r * 256 * 256) + (g * 256) + b)
        return val
        
It is used for the https://github.com/toniarnold/mmba/ LED light controller. The `Toggle` objects in `_main.pd` receive (for white) the [color -16777216] message which changes their background color to something which remotely resembles the color of the LED-bulbs. This works on both Pd 0.47.1 for OS X and Pd 0.46.2 for Raspbian, similar to the native iOS App https://mystrom.ch/de/mystrom-app/ 
On PdParty, the color message gets ignored.

**Comment by danomatika** [comment]
The formatting for acceptable colors changed in newer versions of Pd. I think PdParty may not reflect this change. I'll take a look.

**Comment by danomatika** [comment]
It turns out there are two slightly different algorithms for dealing with negative int colors: when loading from a file and when receiving via a message. PdParty was using only the first and I've now added the second. Fixed with fb2552254d701f0c70472a8a1d82093b570d69fb

**Comment by danomatika** [comment]
Also, note the IEM gui color message is not undocumented:

* create an IEM guide, ie. toggle
* right click on the toggle and choose help
* click on the [pd edit] subpatch

**Comment by danomatika** [comment]
I'll be releasing PdParty 1.2.0 soon which will have this fix. Test when it comes out and reopen this issue if the problem remains.
