### ISSUE TITLE
Frequent thus overlapping netsend messages reproducibly crash PdParty

### ISSUE THREAD

**Issue by toniarnold** [danomatika/PdParty#60]
I've built a https://github.com/toniarnold/mmba/blob/master/bulbs.pd/countdown.pdz testcase (so no actual myStrom bulbs are needed to reproduce), which combined with the https://github.com/toniarnold/mmba/blob/master/bulbs.py server exposed the problem until git-tag `issue1`.

The solution was to consequently synchronize the connect/netsend/disconnect sequence with a spigot (dropping messages that would pile up) to avoid crashes (PdParty immediately closing on iOS 8.4.1) in this excerpt of `bulb.bd`:

![netsend](https://cloud.githubusercontent.com/assets/28350928/26447132/5f0f1f74-4147-11e7-850d-d602b30a372f.png)

Pd 0.47.1 for OS X (on Snow Leopard) seems to be more robust, see issue toniarnold/mmba#1 in the event loop of the `bulbs.py` server: If messages pile up, there results an occasional "netsend: Broken pipe (32)" on the Pd side or a "socket.send() raised exception." on the Python side afterwards (when PdParty is not listening for a reply no more), so concurrent netsend communication seems not to be supported by Pd itself, but exceptions seem to get caught and there are no crashes.

Maybe "replaced CocoaHTTPServer with GCDWebServer, should fix server connection issues" for version "1.1.0: in progress" on https://raw.githubusercontent.com/danomatika/PdParty/master/CHANGES.txt will affect that issue?

**Comment by danomatika** [comment]
Thanks for looking into this.

Might be a difference to how iOS handles sockets. It might kill too many and the number allowed is lower than on a desktop OS.

>Maybe "replaced CocoaHTTPServer with GCDWebServer, should fix server connection issues" for version "1.1.0: in progress"

No. This change is not in a version on the app store yet and concerns an unrelated part of the app, the web server. The only thing there I could think of is if you're testing with the web server on. If so, see if the crash happens with the web server off.

**Comment by toniarnold** [comment]
The WebDAV Server always was off, I transfer .pdz files with FileExplorer's "Open In..." to PdParty. The difference seems to be that on OS X there is only a "netsend: Broken pipe (32)" message on the console (a handled SIGPIPE?) that doesn't cause the application to exit, it just continues with the next connection. On PdParty, I don't get a chance to read any messages after the application has quit.

**Comment by danomatika** [comment]
I believe this was fixed recently in Pd upstream. The fix won't be integrated here until probably after the next version as there needs to be some work on libpd for Pd 0.48.0.

**Comment by danomatika** [comment]
I'll be releasing PdParty 1.2.0 soon which should have the fix for this with the Pd 0.48-2 source. Test when it comes out and reopen this issue if the problem remains.
