### ISSUE TITLE
Feature Request : Audiobus Support (with state saving) (iOS)

### ISSUE THREAD

**Issue by korakios** [danomatika/PdParty#65]
I recently found pdparty is running on iOS. Is it possible adding Audiobus support with state saving?
Thank you for this excellent project :)

**Comment by korakios** [comment]
That was a quick response :)
Totally understand the concept . Well it would be useful to drive audio to other iOS apps...

Unfortunately the AB team does not let an app to support AB3 as IAP ,meaning that people can't support/pay the effort on implementing it.

Thank you for the feedback :)

**Comment by danomatika** [comment]
>meaning that people can't support/pay the effort on implementing it

I have tested it with Audiobus and it does work, however I decided that the amount of work supporting AB was too much for me to do for free as I would probably never use it myself. It would only make sense if someone decides to support my time by paying me to implement and maintain it. This could be through something like Patreon, etc but I have to draw the line somewhere.

**Comment by danomatika** [comment]
And by "I have tested it with Audiobus and it does work", I meant to say that I have added Audiobus to the project as a test a one point and tried it out: https://soundcloud.com/danomatika/eargasm-2017-03-24-223026

It doesn't currently work as far as I know.

**Comment by korakios** [comment]
Maybe adding a "dummy" IAP to support the project would be handy. On one hand you loose a percentage from Apple, on the other hand it's very easy for iOS users (at least for me it's easier than patreon or other services)

Liked the experimental/ambient track !
