### ISSUE TITLE
No Files app support?

### ISSUE THREAD

**Issue by fomalsd** [danomatika/PdParty#67]
Is there a reason why "Supports opening documents in place" property is explicitly set to `false`? iTunes file sharing and web server are quite archaic methods of file transfer from/to iOS.
Set it to `true` and Files app picked up folders without problem (well, file associations don't seem to work, but that's another issue) 
![IMG_1876](https://user-images.githubusercontent.com/10403536/62981220-604f5e80-be31-11e9-8d2e-a7cc2c7a53a9.PNG)

**Comment by danomatika** [comment]
No particular reason other than I don’t have an iPad and have never used the Files app.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com
