### ISSUE TITLE
UI looks bad in iOS 13 when dark theme is on

### ISSUE THREAD

**Issue by fomalsd** [danomatika/PdParty#68]
Compiling project with Xcode 11 beta messes up its looks (tested on iPadOS 13 build 17A5547d):
![gif](https://user-images.githubusercontent.com/10403536/62981921-444cbc80-be33-11e9-88f7-13e4c98c0919.gif)
It'll be fine if it just stays bright in my opinion, this black text on dark grey background is just unreadable

**Comment by danomatika** [comment]
The app is most likely not compatible with iOS 13's dark mode yet. I stick with the release versions of Xcode, so I'll get to it when 11 comes out in the fall, unless you want to submit a PR.

**Comment by danomatika** [comment]
Seems easy enough.

Judging from the Apple doc on [dark mode](https://developer.apple.com/documentation/appkit/supporting_dark_mode_in_your_interface?language=objc), any hard-coded colors should be replaced by interface mode-aware getters such as `[UIColor labelText]` which is available in iOS 13+.

For instance, the browser sets the text color based on if the file can be selected or run. Currently it sets normal items to `[UIColor black]` but that can be changed to `[UIColor labelText]` instead.

**Comment by danomatika** [comment]
Dark mode can also be ignored by setting an override key in Info.plist: `UIUserInterfaceStyle = Light`

**Comment by danomatika** [comment]
I set the interface style to Light for now which should ignore dark mode. Can you do a pull and test? That should hold things over until updating the hard-coded colors later.

**Comment by fomalsd** [comment]
Yep, looks fine now, thanks!
I don't think adapting app to dark mode is worth it, so this one can be closed
