### ISSUE TITLE
Xcode version to use with 1.1.1? (targeting iOS 6)

### ISSUE THREAD

**Issue by fomalsd** [danomatika/PdParty#71]
Wondering what Xcode version was used before "updated to Xcode 9" commit (db0e61e3b86e5ecb14d475a3a50e1228338d73a5) ?

**Comment by danomatika** [comment]
Last version with iOS 6 SDK was probably Xcode 4 or 5. I don't remember. What I used after that to test on my iPhone 3 GS was to manually install the iOS 6 SDK into the Xcode app bundle. This should still work, although the last version I tested was probably with Xcode 8. There is info online about how to do this and you can download an cold Xcode version to extract the SDK folder from the Apple developer site, if you have an account.

**Comment by fomalsd** [comment]
Yeah, I know about [DeviceSupport](https://github.com/filsv/iPhoneOSDeviceSupport) trick, just not sure if Xcode 11 would work with iOS 6 at all, so I thought of trying Xcode version that certainly worked back in the day, perhaps on the old OSX 10.9 machine. Alright, will try 11 first and then 8 if it doesn't. Thanks!

**Comment by fomalsd** [comment]
Yep, it's impossible to make builds for iOS < 7 in Xcode 11:
`OS version (6.0.0) too small, changing to 7.0.0`

**Comment by fomalsd** [comment]
Finally managed to build 1.1.1 for iOS 6 with Xcode 8.2 and iOS 6.x DeviceSupport files. 
Earlier Xcode versions didn't recognise updated syntax in some libraries. 
Had to set up a VM with macOS 10.12 for this because 10.14 refuses to work with Xcode 8.
Hopefully that will be useful for someone, as 4S iPhones perform wonderfully on iOS 6.1.3, which is still signed
