### ISSUE TITLE
Detect Touch Radius?

### ISSUE THREAD

**Issue by korakios** [danomatika/PdParty#78]
Hi, is it possible to detect the radius of the touch on iOS ?

**Comment by danomatika** [comment]
Not currently. The `#touch` events are simple positions and type. You'd like the radius of the "finger blob"?

**Comment by danomatika** [comment]
I could imagine sending additional context info such as touch radius with the `#touch` if a control message is sent to `#pdparty` requesting it. This way the default would keep the old type so as not to break any existing projects which use `[unpack]` to parse the received messages.

**Comment by danomatika** [comment]
* **[r \#touch] _eventType_ _id_ _x_ _y_ _radius_ _force_**: multitouch event\*
  - _eventType_: symbol "down", "xy" (move), or "up"
  - _id_: persistent touch id
  - _x_: x position, normalized 0-1 except for RjDj scenes which use 0-320
  - _y_: y position, normalized 0-1 except for RjDj scenes which use 0-320
  - _radius_: finger/stylus radius in points (pixels)
  - _force_: force into screen, normalized 0-1

This shouldn't break anything as `[unpack]` silently drops extra list items.

**Comment by danomatika** [comment]
This feature now needs to be enabled. Send `#pdparty touch extended 1` when the patch is loaded.

You can the it out by joining the 1.3.0 beta until I can make a proper release. Install the free TestFlight app on your iDevice, then open this TestFlight link:

https://testflight.apple.com/join/17ZZ5AC7
