### ISSUE TITLE
Multicast receive?

### ISSUE THREAD

**Issue by delmenhorst** [danomatika/PdParty#80]
Is it also possible to receive from a multicast ip address OSC massages?

In my cast it doesnt work, and I don't find a solution.

**Comment by danomatika** [comment]
I don't think so. It could be something relatively easy to add in a new release. (I am behind on this, probably in a few weeks.)

**Comment by delmenhorst** [comment]
Cool! Thats would help me a lot. What else is going to be new?

**Comment by danomatika** [comment]
Mainly newer libpd with Pd 0.51 and iOS audio handling overhaul to fix sample rate issues, bluetooth etc.

**Comment by delmenhorst** [comment]
Perfect! :)

**Comment by delmenhorst** [comment]
if you need sombody to test beta versions: I am in.

**Comment by danomatika** [comment]
In the meantime, multicast receiving should work in the 1.3.0 betas using [netreceive] but this is of course not as flexible as the built-in server and settings.

**Comment by danomatika** [comment]
Add multicast receiving in 6ee4280d658feb56c39e1b4747a97fbb05a9eba2.
