### ISSUE TITLE
Force Touch

### ISSUE THREAD

**Issue by delmenhorst** [danomatika/PdParty#82]
Force Touch and the possibilty to use Apple Pencil could bring the use PD-Party to a new level.

https://developer.apple.com/documentation/uikit/uitouch/1618110-force

**Comment by danomatika** [comment]
Latest commit adds radius and force to the #touch message:

**[r \#touch] _eventType_ _id_ _x_ _y_ _radius_ _force_**: multitouch event
  - _eventType_: symbol "down", "xy" (move), or "up"
  - _id_: persistent touch id
  - _x_: x position, normalized 0-1 except for RjDj scenes which use 0-320
  - _y_: y position, normalized 0-1 except for RjDj scenes which use 0-320
  - _radius_: finger/stylus radius in points (pixels)
  - _force_: force into screen, normalized 0-1

**Comment by danomatika** [comment]
Extended touch support now includes a new `#stylus` message for Apple Pencil (or similar devices as reported by the system):

* **[r \#stylus] _eventType_ _id_ _x_ _y_ _radius_ _force_ _azimuth_ _elevation_**: extended touch stylus event
  - _eventType_: symbol "down", "xy" (move), or "up"
  - _id_: persistent touch id
  - _x_: x position, normalized 0-1
  - _y_: y position, normalized 0-1
  - _radius_: radius in points (pixels)
  - _force_: force into screen, normalized 0-1
  - _azimuth_: clockwise rotation angle in radians of cap end around tip -> 0 screen +X axis, 90 -Y, 180 -X, 270 +Y
  - _elevation_: elevation angle in radians above screen -> 0 parallel (down), 90 perpendicular (up)

**Comment by danomatika** [comment]
This feature is now in the PdParty 1.3.0 beta6 build. I don't have a device which supports an Apple Pencil, so you will need to do some testing.

Please join the 1.3.0 beta until I can make a proper release. Install the free TestFlight app on your iDevice, then open this TestFlight link:

https://testflight.apple.com/join/17ZZ5AC7
