### ISSUE TITLE
PdParty not available as an app to open patches

### ISSUE THREAD

**Issue by brizolara** [danomatika/PdParty#83]
Hi all,

I’m in iOS 14.2. When I try to open a pd file (I tried even with local copies of pdparty sample files), pdParty doesn’t appear in the list of possible apps.

And via the Documents folder inside PdParty app, I can’t find any way of accessing local patches.
Am I missing something?

Thanks a lot in advance,

Tiago

**Comment by Ant1r** [comment]
isn't it a duplicate of #69?

**Comment by brizolara** [comment]
Wow, didn't spot it... in fact, it is! Thanks for mentioning.
Closing and waiting for next release then.

**Comment by brizolara** [comment]
Duplicate of #69
