### ISSUE TITLE
multitouch issues

### ISSUE THREAD

**Issue by Josef-N** [danomatika/PdParty#86]
I made a multitouch "keyboard", where a clone object generates notes and other midi data.
Touch-id determines which instance of the clone is used. One very strange thing:
When I press 3 fingers simultaneously and release them, NoteOff (by touch_up_id) is delayed about half of a second. This happens only with 3 voices, not more, not less.
I am far away from being an expert in pd, but I think, the patch is ok. Tried with two different devices, exactly the same. Are you aware of this issue? Not really a big problem, but maybe you could think about it?

**Comment by danomatika** [comment]
I put value editing & touch drag into a separate issue #87 & #88.

**Comment by danomatika** [comment]
Can you share a minimal version of the patch or a patch with similar behavior for testing?

**Comment by Josef-N** [comment]
yes, I can make a minimal version for this issue, but I don’t have it yet. Will send it later.

**Comment by Josef-N** [comment]
here is a minimal version, produces only noteon and noteoff, without any scaling of x or y, 8 voices.
[touch-minimal.zip](https://github.com/danomatika/PdParty/files/5898255/touch-minimal.zip)

**Comment by Josef-N** [comment]
The problem has gone in PdParty 1.3.0-Beta1, fantastic!
solved
