### ISSUE TITLE
Color behavior of PDParty is not compatible with new version of PD.

### ISSUE THREAD

**Issue by delmenhorst** [danomatika/PdParty#93]
When I save a patch with the newest version of pd (0.52-2 on Mac - ARM), the color code of gui objects are saved in hexcode. PD Party cannot read it.

**Comment by danomatika** [comment]
Yup. The current fix is to manually edit the color values back to the old int style. I plan to look into this soon for the next PdParty version.

I wrote a little guide for a recent workshop:
---

New versions of Pd save the GUI object color values in a format that the current version of PdParty can't read correctly. When the patch is opened in PdParty, the GUIs are shown in white and are unresponsive.

To fix this for now, the new style color format needs to be changed to the old style.


1. open patch file in a text editor

2. In GUI objects to show in PdParty,
replace the three hex color values like this:

#fcfcfc #000000 #000000

with this the old integer format:

-262144 -1 -1

(that is black on a white background)

3. save and transfer to PdParty for testing

example:

change

#X obj 130 103 vsl 30 64 0 5000 0 0 empty empty funky\ freq 0 -9 0
10 #00faff #000000 #000000 0 0;

to

#X obj 130 103 vsl 30 64 0 5000 0 0 empty empty funky\ freq 0 -9 0
10 -262144 -1 -1 0 0;

**Comment by Josef-N** [comment]
Thanks for the workaround. Yes, changing the color format works. But I have to do it every single time I save the patch, even if I do not edit anything, just open and save.

**Comment by danomatika** [comment]
This is fixed in the latest commits for next release.

**Comment by Josef-N** [comment]
great, thanks! So we can hope for the new release soon?

 

This is fixed in the latest commits for next release.

**Comment by danomatika** [comment]
I am working on it. You can hope but I can't make any timeline promises.

**Comment by Josef-N** [comment]
all right, thank you!
