### ISSUE TITLE
note off seems to be ignored

### ISSUE THREAD

**Issue by offthesky** [danomatika/PdParty#94]
using a notein routed directly to a noteout object. nothing in between. notes just hang forever when routing from my nanokey wireless through pdparty into apematrix (also tested w sunvox, still same issue). the notes hanhing isnt the case when i test the patch in pdvanilla on my pc. hopefully i am just missing something obvious? although the patch is quite straight forward (it was doing more but to diagnose the note off problem, i just created a very basic notein to noteout patch). am on ios15

attached is the patch im working with. the ctlin/out work fine, the pgmout works okay - its just the notes are getting stuck when going through the notein -> noteout
[nanowireless ios routerPD.zip](https://github.com/danomatika/PdParty/files/8743273/nanowireless.ios.routerPD.zip)
.

**Comment by offthesky** [comment]
also the midiin and midiout modules seem to not send any midi through. when i check the console on both .pd documents, it states: "PureData: some of the audio parameters were not acceptable. attached are the 2 .pd examples
[midithru-notethru not working.zip](https://github.com/danomatika/PdParty/files/8743221/midithru-notethru.not.working.zip)
"

**Comment by danomatika** [comment]
Note off should be fixed in the current master via: https://github.com/danomatika/PdParty/commit/ff89c00fb78af8c89d9a5d48d53a02ed7192813b#diff-6ba81f0e3944b8d9538fe0ca63e8da0cda41b00b240a1a604ad26df8f4d4af5c.

I will put out a PdParty 1.3.0 build over TestFlight soon and send out a mail with info on how to join testing to the pd-list.

**Comment by offthesky** [comment]
excellent, ty! look fwd to testing it out

**Comment by Josef-N** [comment]
Note Offs caused some headache for me, too. I had a good workaround for it, but I like it, how Note Offs are handled in v. 1.3.0 beta now. Much easier to use.

**Comment by danomatika** [comment]
@Josef-N Is the behavior the same as desktop Pd?

**Comment by Josef-N** [comment]
Yes, now it is. My specific problem has been with a keyboard that sends Note Off Velocity, so I never have velocity 0. Desktop Pd converts all NoteOffs to velocity 0 (I guess), PdParty did not. This has advantages and disadvantages.
But I think, it is very good, that desktop Pd and PdParty do exactly the same now.

**Comment by danomatika** [comment]
> But I think, it is very good, that desktop Pd and PdParty do exactly the same now.

That is the goal for these kinds of things.

**Comment by danomatika** [comment]
I'm going to assume this is fixed in the 1.3.0 betas. Please reopen if this is not the case.

**Comment by offthesky** [comment]
> I'm going to assume this is fixed in the 1.3.0 betas. Please reopen if this is not the case.

is there a way to access the betas? if so i could do some tests

**Comment by danomatika** [comment]
Install the free TestFlight app on your iDevice, then open this TestFlight link:

https://testflight.apple.com/join/17ZZ5AC7

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by offthesky** [comment]
awesome will give this a shot this wk

**Comment by offthesky** [comment]
tried the v1.3.0(3) with a basic patch that contained notein<noteout, ctlin<ctlout, bendin<bendout and everything seemed to work fine. tried another patch with just midiin patched straight to the midout object, but that does not seem to work at all. is that a bug?
