### ISSUE TITLE
Graph-On-Parent or dynamic patching support?

### ISSUE THREAD

**Issue by Despair-Bear** [danomatika/PdParty#95]
Just curious if there is a way to get elements from a graph on parent to render in PDParty or (if not) if there is a way to force PDParty to render dynamically created GUI controls.  I'm assuming the initial controls are fetched when it's initializing the patch which is why they wouldn't show up after being created.

**Comment by danomatika** [comment]
Also, dynamic patching works fine but GUIs will not appear since the objects displayed in the canvas are parsed only when the main patch is loaded (separately from libpd).
