### ISSUE TITLE
Color of UI Elements not working

### ISSUE THREAD

**Issue by michaelmariaott** [danomatika/PdParty#97]
Hello, am using PdParty on an iPhone, but the colours of the ui elements do not work. That would not be a problem, if the would default to the default (black-white) colours, however, the slider indicators and the labels seem to default to white, so it is impossible to see them. In the following screenshot from the app, every slider should have a label and an indicator:

![Screen Shot 2022-10-26 at 14 24 18](https://user-images.githubusercontent.com/87768914/198053310-070e0a1d-98e8-4387-9524-a32416e9e98e.png)

This problem only occurs with custom patches, the colours in the test patches seem to work fine. I also tested it with other ui elements. The problem exists for all of them. The only working element is the normal pd number box (both number and label are shown in black).

**Comment by danomatika** [comment]
Yes, this is an issue with the current release on the app store but it is fixed here in master: #93.

Please join the 1.3.0 beta until I can make a proper release. Install the free TestFlight app on your iDevice, then open this TestFlight link:

https://testflight.apple.com/join/17ZZ5AC7

**Comment by michaelmariaott** [comment]
Thank You!
