### ISSUE TITLE
Colour mess when saving patch on Pure Data 0.52.2

### ISSUE THREAD

**Issue by lucretiomsp** [danomatika/PdParty#98]
Hello, first of all thanks a lot for PdParty!
cant't wait to make it work :)
unfortunately I had some problems rendering the colors of my patches so I try to save the examples on my mac without modifications and I have noticed the some behaviour. 
so I opened the patches as text and I noticed that the colors of my GUI are ndered as HEX
for example:

#X obj 49 36 hradio 15 1 0 8 \$0-gui-out \$0-gui-in a_radio 0 -8 0
10 #fcfcfc #000000 #000000 0;

but the same original file was:
#X obj 49 36 hradio 15 1 0 8 \$0-gui-out \$0-gui-in a_radio 0 -8 0
10 -262144 -1 -1 6;

could this be the problem? any way of fixing it by myside?

**Comment by lucretiomsp** [comment]
but it seems to work fineon the best on test flight :)

**Comment by danomatika** [comment]
Yes, it is fixed in the betas. #93 I have submitted PdParty 1.3.0 to Apple for review last week and am currently waiting.

**Comment by danomatika** [comment]
1.3.0 is now approved and should appear on the app store.
