### ISSUE TITLE
Input other than 1+2 not working in Beta 1.3.0

### ISSUE THREAD

**Issue by Josef-N** [danomatika/PdParty#99]
All inputs and outputs are working properly if I start AUM first and PdParty afterwards.
But if I start PdParty without any other app running, inputs are not working except input 1+2. Starting AUM afterwards does not help, too.
In PdParty 1.2 all inputs worked correctly, using a multi-channel interface.
Everything else is fine in 1.3.0!

**Comment by danomatika** [comment]
Please test with 1.3.1 beta which is now on TestFlight.

**Comment by Josef-N** [comment]
Thanks for the quick update. Unfortunately this issue is not fixed. Now also input 1+2 are not working any more. But, as before, when starting AUM first, everything is all right.

**Comment by danomatika** [comment]
Ok. I can't do anything more right now without testing with a multi-channel device directly.

**Comment by Josef-N** [comment]
no problem, it’s not urgent for me. I have my workflow, that’s ok.

**Comment by danomatika** [comment]
I've pushed a 1.3.1 build to TestFlight which should have multi channel audio fixed... at least it works for two devices I have connected to an Edirol Rubix24: the 4 channel outputs work. I don't have a device with more than 2 channels to test.

I have also added a multi_channel test patch in the main tests folder.

**Comment by Josef-N** [comment]
I am sorry, but it is exactly the same as in the previous build, 1.3.1 (1). Tried also with the test patch. Multi channel output has always worked, but not the inputs. I am using K-Mix (8 in - 10 out)

**Comment by Josef-N** [comment]
I found something out now:
If I go to Settings and change the Audio Sample Rate, then all inputs work, regardless which sample rate. Afterwards I can go back to my preferred sample rate.

**Comment by danomatika** [comment]
Is this true with the now-released 1.3.1?

**Comment by Josef-N** [comment]
Yes. Tried in the lates beta and now also in the official release, which are identical, I guess.

**Comment by danomatika** [comment]
At least there is a work-around for now. I will have to check if there is another audio interface at work which provides more than 2 inputs. This is something that I've never really tested in depth before as my use case is stereo in and out.

**Comment by Josef-N** [comment]
OK, of course. But are the stereo inputs working on your devices? I have to do the same work-around for input, even if no audio interface is connected.

**Comment by danomatika** [comment]
> But are the stereo inputs working on your devices?

I guess not yet... Maybe you're right. If so, at least I could check it. Will try, otherwise I can't get to it until mid-January. I just want to make sure the current release isn't *complete* broken, ie. minimum of a workaround.

**Comment by Josef-N** [comment]
No problem. This workaround definitely helps getting audio input to work on current release.

**Comment by danomatika** [comment]
Ok, I am seeing this issue with the Rubix24: plug in interface, start PdParty, no audio input, changing samplerate in settings gets inputs to work.

**Comment by Josef-N** [comment]
good, that you can reproduce this issue!

**Comment by danomatika** [comment]
This should be the fix: 7a8046c92f0ffc1c236729c0fa4d492d1ef2aa6d

**Comment by danomatika** [comment]
PdParty 1.3.2-test1 build is now on TestFlight.

**Comment by danomatika** [comment]
Ah, I see it's still "Waiting for review" and not yet approved for testing. It usually only takes 20-30 minutes after upload to be approved, but I imagine processing times are longer over the holidays.

**Comment by danomatika** [comment]
Ok, 1.3.2-test1 is approved and should be available to install in TestFlight.

**Comment by Josef-N** [comment]
Yesss! 1.3.2 fixed it. All inputs are working. Tested with a multi-channel audio interface connect and also without (for input 1+2 only). Perfect!

**Comment by danomatika** [comment]
👍 Thanks for the confirmation. I am now doing what I should have been for the beginning: set an audio session category for play *and* record, then activate the session so the input and output channel counts are updated.

**Comment by Josef-N** [comment]
Although I have no idea about coding, it seems reasonable to me and is certainly interesting for other developers. Thanks!

**Comment by danomatika** [comment]
PdParty 1.3.2 is now out with the fix.

**Comment by Josef-N** [comment]
great, thanks!
